### ISSUE TITLE
Missing chmod permissions for dnac_aura file

### ISSUE THREAD

**Issue by jillesca** [CiscoDevNet/DNAC-AURA#10]
From the guide [Enhanced Visibility into the Cisco DNA Center using AURA](https://www.cisco.com/c/en/us/support/docs/cloud-systems-management/dna-center/215840-cisco-dna-center-aura-audit-and-upgrad.html#anc7) a very important step is missing, which is making sure`dnac_aura` file is executable. 

Can we add this to the [README.md](https://github.com/CiscoDevNet/DNAC-AURA/blob/master/README.md) file?

This is what the guide says;

> Step 2. Ensure the file dnac_aura is executable.
>
> When the file dnac_aura is copied to the Cisco DNA Center, it is usually not copied as an executable. Run the command to make it executable. If you have used GIT, then this step is not necessary.
>
>$ chmod 755 dnac_aura

Thanks!

**Comment by aradford123** [comment]
thanks.  I have tweaked the readme.  Technically it should be 700, as no other user should run aura.
