### ISSUE TITLE
Scale limit on DN1-HW-APL

### ISSUE THREAD

**Issue by thorsteneb** [CiscoDevNet/DNAC-AURA#2]
For a DN1-HW-APL on 1.3.3.7, the scale limits look right with one exception: Total number of devices is shown as 5,000 max, I expect to see 1,000 max. According to the 1.3.3.x data sheet, 5,000 is the scale number for DN2-HW-APL-XL.

All other scale numbers match a 44-core appliance and are as expected, as far as I could see.

#04:Checking:Scale : Total number of devices (switch, router, wireless controller)
INFO:Total number of devices (switch, router, wireless controller) permitted for Scale : 5000
INFO:Total number of devices (switch, router, wireless controller) Configured on Setup : 12

**Comment by aradford123** [comment]
thanks.. fixed in 1.2.2 - about to push now
