### ISSUE TITLE
Upgrade Path

### ISSUE THREAD

**Issue by fatman00** [CiscoDevNet/DNAC-AURA#6]
When running the Aura Tool on DNAC 2.1.2.7 is says the upgrade path is to go to 2.2.2.3 but the shown version in the GUI and the recommended version is 2.2.2.4
`#26:Checking:DNA Center Upgrade Path to the latest patch of 2.2.2.x
INFO:The Upgrade path to the latest patch release of 2.2.2.x is 2.1.2.7-->2.2.2.3`

AURA: Version:1.5.6

**Comment by aradford123** [comment]
resolved in 1.5.7.  Thanks for raising
