### ISSUE TITLE
Unable to ctrl+c to abort process.

### ISSUE THREAD

**Issue by fatman00** [CiscoDevNet/DNAC-AURA#7]
After running the AURA tool, and typing in the Root password, but trying to abort the GUI login.
`[administration] password for 'ext_username':`
`Aborted!`
`2021-09-28 06:32:15 | INFO | Found non-zero exit code. Do you want to delete RCA temp files? [y/N]`
`^C^C`
`y`
`^C^C^C^C`

**Comment by aradford123** [comment]
are you sure this is from AURA and not the "RCA" tool?

grep "Do you want to delete RCA temp" /usr/local/bin/rca                            
    log "Found non-zero exit code. Do you want to delete RCA temp files? [y/N] "

**Comment by fatman00** [comment]
Year, sorry about that, just had a brainfart, please just delete this issue :-)
